[package]
name = "ipapi"
version = "2.0.0"
authors = ["Squared <squared@codebrew.fr> (https://squared.codebrew.fr)"]
license = "WTFPL"

[dependencies]
rouille = "2.1"
maxminddb = "0.10"
serde_json = "1.0"
